[package]
name = "monero"
description = "Rust Monero Library."
keywords = ["monero"]
version = "0.7.0"
authors = ["h4sh3d <h4sh3d@protonmail.com>"]
license = "MIT"
homepage = "https://github.com/monero-rs/monero-rs"
repository = "https://github.com/monero-rs/monero-rs"
documentation = "https://docs.rs/monero"
readme = "README.md"
include = [
    "src/*",
    "README.md",
    "LICENSE",
]

edition = "2018"

[features]
default = ["full"]
full = ["fixed-hash/std", "fixed-hash/rand"]
serde_support = ["serde", "serde-big-array"]

[dependencies]
hex = "0.4"
byteorder = "1"
keccak-hash = "0.5"
base58-monero = "0.2"
serde = { version = "1.0", features = ["derive"], optional = true }
serde-big-array = {version = "0.2.0", optional = true}
curve25519-dalek= {version = "2.0", features = ["serde"]}

[dependencies.fixed-hash]
version = "0.6"
default-features = false

[badges]
travis-ci = { repository = "monero-rs/monero-rs", branch = "master" }
